Página de detalhe para um anime.
MarcosXavier93/Project-Stack-Rate---PSR---ReactJs pull request #12
Opened 2021-07-08 22:47 UTC by guszille

## Qual o problema inicial?
Sem página de detalhe para exibir as informações gerais e médias em comparação com a nota da pessoa autenticada.

## O que esse Pull Request faz?
Implementação inicial da página de detalhe do anime.

## Como testar?
Basta navegar para a página. No atual momento é necessário alterar o componente principal que está sendo exibido no arquivo **index.js**.

**Issues relacionadas:**
Close #6 - Criar a página de detalhes (só o front)

2021-07-08 23:57 UTC, PierreVieira commented on src/detail_screen/anime.js
> +          <div className='divider'></div>
Essa tag pode ser colapsada já que não tem conteúdo dentro
```suggestion
          <div className='divider'/>
```

2021-07-08 23:57 UTC, PierreVieira commented on src/detail_screen/anime.js
> +        <iframe src='https://www.youtube.com/embed/ocQ6PDiP014' title='YouTube video' frameBorder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture'
```suggestion
        <iframe src='https://www.youtube.com/embed/ocQ6PDiP014' title='YouTube video' frameBorder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowFullScreen/>
```

2021-07-08 23:58 UTC, PierreVieira commented on src/detail_screen/anime.js
> +const Header = props => {
Já que props não é utilizado podemos obstruí-lo
```suggestion
const Header = () => {
```

2021-07-08 23:59 UTC, PierreVieira commented on src/detail_screen/anime.js
> +    <div></div>
```suggestion
    <div/>
```

2021-07-08 23:59 UTC, PierreVieira commented on src/detail_screen/anime.js
> +const Anime = props => {
```suggestion
const Anime = () => {
```

2021-07-09 00:01 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  box-shadow: 0px 2px 4px 3px var(--grey-5);
```suggestion
  box-shadow: 0 2px 4px 3px var(--grey-5);
```

2021-07-09 00:02 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  margin: 0px;
Só pra deixar mais limpo
```suggestion
  margin: 0;
```

2021-07-09 00:02 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  padding: 16px 0px;
```suggestion
  padding: 16px 0;
```

2021-07-09 00:09 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  font-family: 'Roboto';
Recomenda-se usar famílias de fontes genéricas em fontes customizadas:
https://stackoverflow.com/a/31378694/11111289
```suggestion
  ffont-family: 'Roboto', serif;
```

2021-07-09 00:10 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  margin: 0px;
```suggestion
  margin: 0;
```

2021-07-09 00:10 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  margin: 32px 0px;
```suggestion
  margin: 32px 0;
```

2021-07-09 00:11 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  font-family: 'Roboto';
```suggestion
  font-family: 'Roboto', serif;
```

2021-07-09 00:11 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  margin: 0px;
```suggestion
  margin: 0;
```

2021-07-09 00:11 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  font-family: 'Roboto';
```suggestion
  font-family: 'Roboto', serif;;
```

2021-07-09 00:12 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  margin: 0px 0px 24px 0px;
```suggestion
  margin: 0 0 24px 0;;
```

2021-07-09 00:12 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  margin: 0px;
```suggestion
  margin: 0;
```

2021-07-09 00:12 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  font-family: 'Quicksand';
```suggestion
  font-family: 'Quicksand', serif;
```

2021-07-09 00:13 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  margin: 0px 0px 24px 0px;
```suggestion
  margin: 0 0 24px 0;
```

2021-07-09 00:13 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  font-family: 'Quicksand';
```suggestion
  font-family: 'Quicksand', serif;
```

2021-07-09 00:13 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  margin: 0px;
```suggestion
  margin: 0;
```

2021-07-09 00:14 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  font-family: 'Roboto';
```suggestion
  font-family: 'Roboto', serif;
```

2021-07-09 00:14 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  font-family: 'Roboto';
```suggestion
  font-family: 'Roboto', serif;
```

2021-07-09 00:14 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  box-shadow: 0px 1px 1px var(--grey-5);
```suggestion
  box-shadow: 0 1px 1px var(--grey-5);
```

2021-07-09 00:15 UTC, PierreVieira commented on src/detail_screen/anime.css
> +  font-family: 'Roboto';
```suggestion
  font-family: 'Roboto', serif;
```

2021-07-09 00:22 UTC, PierreVieira requested changes
Tudo funciona muito bem com exceção dessa caixa de diálogo:

<div align="center"><img width="500" src="https://user-images.githubusercontent.com/49538805/125005559-69073a00-e032-11eb-9001-6f6c25f7297f.png"></div>

Acredito que apesar da implementação ser só do front essa parte do dialog deveria funcionar.
De resto tá 100%

2021-07-09 22:34 UTC, guszille commented
@PierreVieira Fiz as correções e a implementação da ação do diálogo dentro de um **commit** separado.

2021-07-10 14:21 UTC, PierreVieira commented on .npmrc
> +package-lock=false
Esse arquivo `.npmrc` deveria subir para o remoto?
Talvez valhe a pena inserí-lo no git ignore

2021-07-10 14:22 UTC, PierreVieira reviewed
Avaliar se esse `.npmrc` deve ir para o remoto

2021-07-10 20:55 UTC, guszille commented on .npmrc
> +package-lock=false
Esse arquivo serve para informar ao **npm** para não criar um arquivo **package-lock.json**. Vamos evitar conflitos em cima desse arquivo por hora.

2021-07-10 20:59 UTC, PierreVieira approved these changes

2021-07-10 20:59 UTC, merged